[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "MAGPIE"
authors = [{name = "Anum Glasgow", email = "ag4522@cumc.columbia.edu"}]
dynamic = ["version", "description"]
